language: c

env:
  global:
    - LUAROCKS=2.2.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit

before_install:
  - source .travis/setenv_lua.sh

install:
  - luarocks install luacoverage
  - luarocks install luaunit

script:
  - cd lua/scripts/tests
  - lua testSuite.lua
  - luacov
  - cat luacov.report.out
