version: "3"
services:
    ac-lua-server:
        build: .
        ports:
            - "28763:28763/udp"
            - "28764:28764/udp"
        volumes:
            - ./test-server/config:/ac-server/config:rw
            - ./test-server/packages:/ac-server/packages:rw
            - ./src/config:/ac-server/lua/config:rw
            - ./src:/ac-server/lua/scripts:rw
            - ./test-server/geoip-data:/usr/share/GeoIP
        networks:
          - database
        depends_on:
          - database
          - geoip-updater

    database:
      image: mysql/mysql-server:5.7
      container_name: database
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: assaultcube_gema
        MYSQL_USER: assaultcube
        MYSQL_PASSWORD: password
      networks:
        - database
      volumes:
        - db-data:/var/lib/mysql:rw

    geoip-updater:
      image: maxmindinc/geoipupdate
      environment:
        GEOIPUPDATE_ACCOUNT_ID: <your account id>
        GEOIPUPDATE_LICENSE_KEY: <your license key>
        GEOIPUPDATE_EDITION_IDS: GeoLite2-Country
        GEOIPUPDATE_FREQUENCY: 24
      volumes:
        - ./test-server/geoip-data:/usr/share/GeoIP
networks:
  database:

volumes:
  db-data:
