---
-- @author wesen
-- @copyright 2018 wesen <wesen-ac@web.de>
-- @release 0.1
-- @license MIT
--

local BaseTag = require("Output/TemplateRenderer/TableTemplateParser/Tags/BaseTag");
local RowFieldTag = require("Output/TemplateRenderer/TableTemplateParser/Tags/RowFieldTag");

---
-- Represents a row.
--
-- @type RowTag
--
local RowTag = setmetatable({}, {__index = BaseTag});


---
-- The list of tag types that are closed by this tag
--
-- @tfield BaseTag[] closeTagTypes
--
RowTag.closeTagTypes = {RowFieldTag, RowTag};


---
-- RowTag constructor.
--
-- @treturn RowTag The RowTag instance
--
function RowTag:__construct()

  local instance = BaseTag:__construct();
  setmetatable(instance, {__index = RowTag});

  return instance;

end

getmetatable(RowTag).__call = RowTag.__construct;


-- Protected Methods

---
-- Adds an inner text to the generated table rows.
--
-- @tparam table _tableRows The generated table rows
-- @tparam string _innerText The inner text
--
function RowTag:addInnerTextToTableRows(_tableRows, _innerText)

  if (#_tableRows == 0) then
    _tableRows[1] = {};
  end
  table.insert(_tableRows[1], _innerText);

end

---
-- Adds an inner tag to the generated table rows.
--
-- @tparam table _tableRows The generated table rows
-- @tparam table _innerTagTable The table that was generated by the inner tag
--
function RowTag:addInnerTagTableToTableRows(_tableRows, _innerTagTable)

  if (#_tableRows == 0) then
    _tableRows[1] = {};
  end

  -- The inner tags are row field and custom field tags only
  table.insert(_tableRows[1], _innerTagTable);

end


return RowTag;
